version: '3.1'
services:
  stat-server:
    build:
      context: ./stat-service/stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/dbstats
      SPRING_DATASOURCE_USER: admin
      SPRING_DATASOURCE_PASSWORD: admin

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dbstats
    volumes:
      - pg-data-stats:/var/lib/postgresql/data/

  ewm-service:
    build:
      context: ./main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/dbmain
      SPRING_DATASOURCE_USER: admin
      SPRING_DATASOURCE_PASSWORD: admin
      STATS_SERVER_URL: http://stat-server:9090

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: dbmain
    volumes:
      - pg-data-main:/var/lib/postgresql/data/

volumes:
  pg-data-stats:
  pg-data-main: